sonar.projectKey=Youchenjiang_ctfd-kit
sonar.organization=youchenjiang
sonar.sources=.
sonar.sourceEncoding=UTF-8

# SonarCloud Automatic Analysis Configuration
# Global exclusions
sonar.exclusions=ctfd/database/**,ctfd/challenges/**,ctfd/automation/**,ctfd/plugins/**/assets/**,**/*.sql,**/*.exe,**/*.obj,**/*.pdb,**/*.patch

# Duplication detection (CPD) exclusions
sonar.cpd.exclusions=ctfd/challenges/**,ctfd/database/**,ctfd/plugins/**,ctfd/automation/**,**/*.sql,**/*.c,**/*.h,**/*.md
